AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MySQLDatabase:
    Type: AWS::RDS::DBCluster
    Properties:
      DBName: f-mysql-lookup-nodejs-db
      EngineMode: serverless
      Engine: aurora-mysql
      EnableHttpEndpoint: TRUE
  MySQLSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: f-mysql-lookup-nodejs-secret
      Description: f-mysql-lookup-nodejs mysql secret
      GenerateSecretString:
        SecretStringTemplate: !Join ['', ['{ "username": "', 'mysql', '" }']]
        GenerateStringKey: 'password'
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
  AuroraServerlessPostgresClusterSecretAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref MySQLSecret
      TargetId: !Ref MySQLDatabase
      TargetType: AWS::RDS::DBCluster
  InitRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
      Path: /
      Policies:
          -
            PolicyName: CloudwatchLogs
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                -
                  Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                  Resource:
                    - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
                -
                  Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
                -
                  Effect: Allow
                  Action:
                    - rds-data:ExecuteStatement
                  Resource:
                    - !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:*"
  InitFunction:
    Type: AWS::Lambda::Function
    DeletionPolicy: Retain
    Properties:
      Role: !GetAtt 'InitRole.Arn'
      Handler: index.handler
      Runtime: python3.9
      Timeout: 30
      Code:
        ZipFile: |
          import boto3, json, urllib3

          http = urllib3.PoolManager()
          rdsdata = boto3.resource('rds-data')

          def send(event, context, responseStatus, responseData):
            responseUrl = event['ResponseURL']
            responseBody = {
                'Status' : responseStatus,
                'Reason' : "See the details in CloudWatch Log Stream: {}".format(context.log_stream_name),
                'PhysicalResourceId' : context.log_stream_name,
                'StackId' : event['StackId'],
                'RequestId' : event['RequestId'],
                'LogicalResourceId' : event['LogicalResourceId'],
                'NoEcho' : False,
                'Data' : responseData
            }
            json_responseBody = json.dumps(responseBody)
            headers = {
                'content-type' : '',
                'content-length' : str(len(json_responseBody))
            }
            try:
                response = http.request('PUT', responseUrl, headers=headers, body=json_responseBody)
            except Exception as e:
                print("send(..) failed executing http.request(..):", e)


          def handler(event, context):
            print("Received event: " + json.dumps(event, indent=2))

            if event['RequestType'] == 'Delete':
              send(event, context, 'SUCCESS', {'Data': 'Delete complete'})
            else:
              try:
                secretArn = dynamodb.Table(event['ResourceProperties']['SecretArn'])
                resourceArn = dynamodb.Table(event['ResourceProperties']['ResourceArn'])
                database =
                sql="create table customers(id varchar(10), fname varchar(100), lname varchar(100));"
                rds.execute_statement(database='f-mysql-lookup-nodejs-db', sql=sql, resourceArn=resourceArn, secretArn=secretArn);
                sql="insert into customer values ('1','John','Doe'),('2','Jane','Doe'),('3','Carlos','Salazar'),('4','Diego','Ramirez'),('5','Mary','Major'),('6','Richard','Roe'); "
                rds.execute_statement(database='f-mysql-lookup-nodejs-db', sql=sql, resourceArn=resourceArn, secretArn=secretArn);
              except Exception as e:
                print(e)
                send(event, context, 'FAILED', {'Data': 'Insert failed'})
  InitializeMySQLDB:
      Type: Custom::InitFunction
      DependsOn: MySQLDatabase
      Properties:
        ServiceToken:
          Fn::GetAtt: [ InitFunction , "Arn" ]
        SecretArn:
          Fn::GetAtt: [ MySQLSecret , "Arn" ]
        ResourceArn:
          Fn::GetAtt: [ MySQLDatabase, "Arn" ]
