name: GitHub Actions Demo
on: [push]
jobs:
  DeployCode:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          folders=""
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
          for file in ${files[@]}; do
            folders="$folders $(dirname $file)"
          done
          folders="$folders" | tr " " "\n" | sort | uniq | tr "\n" " "
          cd bin
          for folder in $folders; do
              ./deployFunction.sh $category $function ${{ secrets.S3_LOC }} ${{ secrets.IAM_ROLE }} ${{ secrets.CLUSTER }} ${{ secrets.DB }} ${{ secrets.USER }} ${{ secrets.SCHEMA }}
              ./testFunction.sh $category $function ${{ secrets.CLUSTER }} ${{ secrets.DB }} ${{ secrets.USER }} ${{ secrets.SCHEMA }}
          done
